# Generated by Django 6.1.1 on 2026-10-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUser',
            fields=[
            ],
            options={
                'verbose_name': 'Usuario Normal',
                'verbose_name_plural': '2. Usuarios Normales',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Usuarios.customuser',),
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
            ],
            options={
                'verbose_name': 'Usuario Staff',
                'verbose_name_plural': '1. Usuarios Staff',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Usuarios.customuser',),
        ),
        migrations.AddField(
            model_name='customuser',
            name='huella_template',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
